# Generated by Django 4.1.3 on 2022-11-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_zxc_scores'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='zxc_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='zxc_scores',
            field=models.SmallIntegerField(default=1000),
        ),
    ]
